name: fss_example
description: Simple test application and examples for fss styling
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fss:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: StyleScript
      fonts:
        - asset: assets/StyleScript-Regular.ttf
          style: normal